### ISSUE TITLE
Timer needs to have adjustable max count

### ISSUE THREAD

**Issue by johnbentcope** [johnbentcope/iron_violet#18]
Timer has fixed max count. that's not great for game

**Comment by KaseyHDL** [comment]
![Screenshot_20240310-144649.png](https://github.com/johnbentcope/iron_violet/assets/47794776/ac8ee3bd-e1ce-4d0c-8967-220f62441fa6)

**Comment by KaseyHDL** [comment]
I screwed this one up, it is configurable but instead of each flipflop cascading to the next, they just feed back into themselves. Also, this doesn't even work I think oops

**Comment by KaseyHDL** [comment]
timer should work now hopefully
