### ISSUE TITLE
Nice project!

### ISSUE THREAD

**Issue by urish** [johnbentcope/iron_violet#34]
Great to see another Simon Says game on Tiny Tapeout.

Can you please move the documentation from docs/INDEX.md to docs/info.md? This way it will appear in the Tiny Tapeout datasheet (you can use your own headings, no need to adhere to the heading in the Tiny Tapeout template).

Also, please fill in the "pinout" in info.yaml, so other people (and future you) will know which pins go to the LED, buttons, and speaker.

**Comment by johnbentcope** [comment]
Resolved in latest commit, new pull request filed. https://github.com/TinyTapeout/tinytapeout-06/pull/434
