### ISSUE TITLE
Stack.v

### ISSUE THREAD

**Issue by matt02j** [johnbentcope/iron_violet#4]
![image](https://github.com/johnbentcope/iron_violet/assets/33326270/84bce438-bf7f-44c1-b73b-f84dbfe7c845)

recommend reducing width and adding an encode/decode

**Comment by matt02j** [comment]
to be more specific, i would do all the logic on 2-bit signals and only do the encode/decode at top level IO

**Comment by johnbentcope** [comment]
fixd
